replicaCount: 4

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.guardrails.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: api-guardrails-io
      hosts:
        - api.guardrails.io

ingressBadges:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /v2/badges/$1
  hosts:
    - host: badges.guardrails.io
      paths:
        - path: '/(.*)'
          pathType: ImplementationSpecific
  tls:
    - secretName: badges-guardrails-io
      hosts:
        - badges.guardrails.io

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1024Mi

env:
  - name: SENTRY_DSN
    value: 'https://a4ed61ce4b404b03b97618ded52dc6d5@sentry.io/1225444'
  - name: NEW_RELIC_APP_NAME
    value: 'api'
  - name: NEW_RELIC_ENABLED
    value: 'true'
