export enum ActionChangeLogType {
  ACTION_CREATED = 'ACTION_CREATED',
  ACTION_UPDATED = 'ACTION_UPDATED',
  ACTION_DELETED = 'ACTION_DELETED',
  ACTION_REQUESTED = 'ACTION_REQUESTED',
  ACTION_APPROVED = 'ACTION_APPROVED',
  ACTION_REJECTED = 'ACTION_REJECTED'
}
